Imported Upstream version 2.3.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -831,13 +831,16 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-64bit-gcc	Try to compile 64bit (only tested on Sparc Solaris 9).
   --disable-dependency-tracking Speeds up one-time builds
   --enable-dependency-tracking  Do not reject slow dependency extractors
   --enable-debug          enable debugging options (bugreports and developers only)
   --enable-profile        enable profiling options (developers only)
-  --enable-sourcefire     Enable Sourcefire specific build options
+  --enable-sourcefire      Enable Sourcefire specific build options
   --enable-perfmonitor     Enable perfmonitor preprocessor
   --enable-linux-smp-stats Enable statistics reporting through proc
+  --enable-inline         Use the libipq interface for inline snort
+  --enable-ipfw            Enable ipfw Divert mode for use with inline
   --enable-flexresp       Flexible Responses on hostile connection attempts
 
 Optional Packages:
@@ -853,6 +856,8 @@ Optional Packages:
   --with-odbc=DIR         support for odbc
   --with-postgresql=DIR   support for postgresql
   --with-oracle=DIR       support for oracle
+  --with-libipq-includes=DIR  libipq include directory
+  --with-libipq-libraries=DIR  libipq library directory
 
 Some influential environment variables:
   CC          C compiler command
@@ -1473,7 +1478,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=snort
- VERSION=2.2.0
+ VERSION=2.3.0
 
 
 cat >>confdefs.h <<_ACEOF
@@ -1599,6 +1604,14 @@ INSTALL_STRIP_PROGRAM="\${SHELL} \$(install_sh) -c -s"
 
 
 
+
+# Since we get -O2 from configure defaults, which doesn't work in 64bit
+# mode, let's make some changes here before calling _CC macros.
+# Check whether --enable-64bit-gcc or --disable-64bit-gcc was given.
+if test "${enable_64bit_gcc+set}" = set; then
+  enableval="$enable_64bit_gcc"
+   CFLAGS="-O0 -g" CC="gcc -m64"; export CFLAGS CC
+fi;
 rm -f .deps 2>/dev/null
 mkdir .deps 2>/dev/null
 if test -d .deps; then
@@ -2683,7 +2696,6 @@ else
   RANLIB="$ac_cv_prog_RANLIB"
 fi
 
-
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -3329,14 +3341,13 @@ CCDEPMODE=depmode=$am_cv_CC_dependencies_compiler_type
       CFLAGS="$CFLAGS -Wall "
  fi
 
-
 # Check whether --enable-debug or --disable-debug was given.
 if test "${enable_debug+set}" = set; then
   enableval="$enable_debug"
    if test -n "$GCC"; then
                     CFLAGS="-O0 -DDEBUG -g"
                   else
-                    CFLAGS="$CFLAGS -DDEBUG"cd
+                    CFLAGS="$CFLAGS -DDEBUG"
                   fi
 
 fi;
@@ -6177,12 +6188,12 @@ if test "$with_mysql" != "no"; then
   if test "$with_mysql" = "yes"; then
     mysql_directory="$default_directory";
     mysql_fail="yes"
-  elif test -d $withval; then
+  elif test -d "$withval"; then
     mysql_directory="$withval"
-    mysql_fail="no"
+    mysql_fail="yes"
   elif test "$with_mysql" = ""; then
     mysql_directory="$default_directory";
-    mysql_fail="no"
+    mysql_fail="yes"
   fi
 
   echo "$as_me:$LINENO: checking for mysql" >&5
@@ -6322,7 +6333,7 @@ _ACEOF
 
 fi
 
-      LIBS="${LIBS} -lmysqlclient"
+      LIBS="-lmysqlclient ${LIBS}"
     fi
   fi
 fi
@@ -6616,6 +6627,281 @@ if test "${enable_linux_smp_stats+set}" = set; then
   enableval="$enable_linux_smp_stats"
   CFLAGS="$CFLAGS -DLINUX_SMP"
 fi;
+
+# Check whether --enable-inline or --disable-inline was given.
+if test "${enable_inline+set}" = set; then
+  enableval="$enable_inline"
+  enable_inline="$enableval"
+else
+  enable_inline="no"
+fi;
+
+# Check whether --enable-ipfw or --disable-ipfw was given.
+if test "${enable_ipfw+set}" = set; then
+  enableval="$enable_ipfw"
+  enable_ipfw="$enableval"
+else
+  enable_ipfw="no"
+fi;
+if test "$enable_inline" != "no"; then
+   if test "$enable_inline" = "yes"; then
+        CFLAGS="$CFLAGS -DGIDS"
+        if test "$enable_ipfw" = "yes"; then
+            CFLAGS="$CFLAGS -DIPFW"
+        else
+
+# Check whether --with-libipq_includes or --without-libipq_includes was given.
+if test "${with_libipq_includes+set}" = set; then
+  withval="$with_libipq_includes"
+  with_libipq_includes="$withval"
+else
+  with_libipq_includes=no
+fi;
+
+# Check whether --with-libipq_libraries or --without-libipq_libraries was given.
+if test "${with_libipq_libraries+set}" = set; then
+  withval="$with_libipq_libraries"
+  with_libipq_libraries="$withval"
+else
+  with_libipq_libraries=no
+fi;
+           if test "$with_libipq_includes" != "no"; then
+                CPPFLAGS="${CPPFLAGS} -I${with_libipq_includes}"
+           fi
+
+           if test "${ac_cv_header_libipq_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for libipq.h" >&5
+echo $ECHO_N "checking for libipq.h... $ECHO_C" >&6
+if test "${ac_cv_header_libipq_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_libipq_h" >&5
+echo "${ECHO_T}$ac_cv_header_libipq_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking libipq.h usability" >&5
+echo $ECHO_N "checking libipq.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <libipq.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking libipq.h presence" >&5
+echo $ECHO_N "checking libipq.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <libipq.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: libipq.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: libipq.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libipq.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: libipq.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: libipq.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: libipq.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libipq.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: libipq.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libipq.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: libipq.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for libipq.h" >&5
+echo $ECHO_N "checking for libipq.h... $ECHO_C" >&6
+if test "${ac_cv_header_libipq_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_libipq_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_libipq_h" >&5
+echo "${ECHO_T}$ac_cv_header_libipq_h" >&6
+
+fi
+if test $ac_cv_header_libipq_h = yes; then
+  :
+else
+  { { echo "$as_me:$LINENO: error: libipq.h not found ..." >&5
+echo "$as_me: error: libipq.h not found ..." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+           if test "$with_libipq_libraries" != "no"; then
+                LDFLAGS="${LDFLAGS}  -L${with_libipq_libraries}"
+           fi
+
+           LIPQ=""
+
+echo "$as_me:$LINENO: checking for ipq_set_mode in -lipq" >&5
+echo $ECHO_N "checking for ipq_set_mode in -lipq... $ECHO_C" >&6
+if test "${ac_cv_lib_ipq_ipq_set_mode+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lipq  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char ipq_set_mode ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+ipq_set_mode ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_ipq_ipq_set_mode=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_ipq_ipq_set_mode=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_ipq_ipq_set_mode" >&5
+echo "${ECHO_T}$ac_cv_lib_ipq_ipq_set_mode" >&6
+if test $ac_cv_lib_ipq_ipq_set_mode = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBIPQ 1
+_ACEOF
+
+  LIBS="-lipq $LIBS"
+
+else
+  LIPQ="no"
+fi
+
+
+           if test "$LIPQ" = "no"; then
+               echo
+               echo "   ERROR!  Libipq library/headers not found, go get it from"
+               echo "   www.netfilter.org or use the --with-libipq-* options, "
+               echo "   if you have it installed in unusual place"
+               echo
+               exit
+           fi
+        fi
+
+        LIBNET_INC_DIR=""
+        echo "$as_me:$LINENO: checking \"for libnet.h version 1.0.x\"" >&5
+echo $ECHO_N "checking \"for libnet.h version 1.0.x\"... $ECHO_C" >&6
+        libnet_dir="/usr/include /usr/local/include"
+        for i in $libnet_dir; do
+            if test -r $i/libnet.h; then
+                LIBNET_INC_DIR=$i
+            fi
+        done
+
+        if test "$LIBNET_INC_DIR" != ""; then
+            if eval "grep LIBNET_VERSION $LIBNET_INC_DIR/libnet.h | grep -v 1.0 >/dev/null"; then
+
+   echo
+   echo
+   echo "**********************************************"
+   echo "  ERROR: unable to find" "libnet 1.0.x (libnet.h)"
+   echo "  checked in the following places"
+   for i in `echo $tmp`; do
+     echo "        $i"
+   done
+   echo "**********************************************"
+   echo
+   exit
+
+            fi
+            CFLAGS="${CFLAGS} `libnet-config --defines` `libnet-config --cflags`"
+            LIBS="${LIBS} `libnet-config --libs`"
+            CPPFLAGS="${CPPFLAGS} -I${LIBNET_INC_DIR}"
+            echo "$as_me:$LINENO: result: $i" >&5
+echo "${ECHO_T}$i" >&6
+        else
+            echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+            { { echo "$as_me:$LINENO: error: \"libnet 1.0.x could not be found.  please download and install the library from http://www.packetfactory.net/libnet/\"" >&5
+echo "$as_me: error: \"libnet 1.0.x could not be found.  please download and install the library from http://www.packetfactory.net/libnet/\"" >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    fi
+fi
 
 # Check whether --enable-flexresp or --disable-flexresp was given.
 if test "${enable_flexresp+set}" = set; then
@@ -7524,7 +7810,7 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL}'
 
 test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
-ac_config_files="$ac_config_files Makefile src/Makefile src/sfutil/Makefile src/detection-plugins/Makefile src/output-plugins/Makefile src/preprocessors/Makefile src/preprocessors/HttpInspect/Makefile src/preprocessors/HttpInspect/include/Makefile src/preprocessors/HttpInspect/utils/Makefile src/preprocessors/HttpInspect/anomaly_detection/Makefile src/preprocessors/HttpInspect/client/Makefile src/preprocessors/HttpInspect/event_output/Makefile src/preprocessors/HttpInspect/mode_inspection/Makefile src/preprocessors/HttpInspect/normalization/Makefile src/preprocessors/HttpInspect/server/Makefile src/preprocessors/HttpInspect/session_inspection/Makefile src/preprocessors/HttpInspect/user_interface/Makefile src/preprocessors/flow/Makefile src/preprocessors/flow/int-snort/Makefile src/preprocessors/flow/portscan/Makefile src/parser/Makefile doc/Makefile contrib/Makefile etc/Makefile rules/Makefile templates/Makefile src/win32/Makefile"
+ac_config_files="$ac_config_files Makefile src/Makefile src/sfutil/Makefile src/detection-plugins/Makefile src/output-plugins/Makefile src/preprocessors/Makefile src/preprocessors/HttpInspect/Makefile src/preprocessors/HttpInspect/include/Makefile src/preprocessors/HttpInspect/utils/Makefile src/preprocessors/HttpInspect/anomaly_detection/Makefile src/preprocessors/HttpInspect/client/Makefile src/preprocessors/HttpInspect/event_output/Makefile src/preprocessors/HttpInspect/mode_inspection/Makefile src/preprocessors/HttpInspect/normalization/Makefile src/preprocessors/HttpInspect/server/Makefile src/preprocessors/HttpInspect/session_inspection/Makefile src/preprocessors/HttpInspect/user_interface/Makefile src/preprocessors/flow/Makefile src/preprocessors/flow/int-snort/Makefile src/preprocessors/flow/portscan/Makefile src/parser/Makefile doc/Makefile contrib/Makefile schemas/Makefile rpm/Makefile etc/Makefile rules/Makefile templates/Makefile src/win32/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -8036,6 +8322,8 @@ do
   "src/parser/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/parser/Makefile" ;;
   "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
   "contrib/Makefile" ) CONFIG_FILES="$CONFIG_FILES contrib/Makefile" ;;
+  "schemas/Makefile" ) CONFIG_FILES="$CONFIG_FILES schemas/Makefile" ;;
+  "rpm/Makefile" ) CONFIG_FILES="$CONFIG_FILES rpm/Makefile" ;;
   "etc/Makefile" ) CONFIG_FILES="$CONFIG_FILES etc/Makefile" ;;
   "rules/Makefile" ) CONFIG_FILES="$CONFIG_FILES rules/Makefile" ;;
   "templates/Makefile" ) CONFIG_FILES="$CONFIG_FILES templates/Makefile" ;;
