Fix how the files are generated and use Perl instead of bash's echo as the latter will interpret content in the configuration fil and will botch it - Fix typo in the configuration file which moved the configuration file to database.conf instead of just the database configuration.  - Only generate content in database.conf if the default configuration file contains the DBSTART line from previous versions.  - Be cautious, if an empty configuration file is generated then abort. (Closes: 607951)

diff --git a/debian/snort-common.preinst b/debian/snort-common.preinst
--- a/debian/snort-common.preinst
+++ b/debian/snort-common.preinst
@@ -13,45 +13,48 @@ GENCONF="/etc/snort/snort.conf"
 
 case "$1" in
     install)
+        # TODO: Having an empty file here is a little bit weird for sysadmins
+        # it might be better to have a file with just a comment saying
+        # that it does nothing, but then it makes it difficult for
+        # snort-common to detect if he has to purge it on postrm
         # make sure the database configuration file exists
-        touch $DBCONF
+        [ ! -e "$DBCONF" ] && touch $DBCONF
     ;;
     upgrade)
          # earlier versions modified /etc/snort/snort.conf directly for the
          # DB stuff, we splitt it off in a sepperate file, to ensure smooth
          # upgrades
-         if dpkg --compare-versions "$2" le "2.8.5.2-2";
+         if dpkg --compare-versions "$2" eq "2.8.5.2-3" 
+         then
+         # Fix bug from previous release that resulted in an
+         # incorrect database.conf being generated
+            if [ -e "$DBCONF" -a -e "$GENCONF" ] && grep -q "http://www.snort.org" $DBCONF
+            then    
+                rm -f $DBCONF
+                touch $DBCONF
+            fi
+        fi
+
+         if dpkg --compare-versions "$2" le "2.8.5.2-3" && grep -q "(#DBSTART#)" $GENCONF 
          then
              GENCONF_TEMPFILE=`mktemp`
              DBCONF_TEMPFILE=`mktemp`
-             WRITE_DB=0
-             WRITE_GEN=1
              # Look into the generated configuration file to see if
              # there is a database definition, if there is, transparently
              # copy it over to its new location
-             cat $GENCONF | while read LINE
-             do
-                 if [ "$LINE" = "# (#DBEND#)" ]
-                 then
-                     WRITE_DB=0
-                     WRITE_GEN=1
-                 fi
-                 if [ $WRITE_DB -eq 1 ]
-                 then
-                     echo $LINE >> $DBCONF_TEMPFILE
-                 fi
-                 if [ $WRITE_GEN -eq 1 ]
-                 then
-                     echo $LINE >> $GENCONF_TEMPFILE
-                 fi
-                 if [ "$LINE" = "# (#DBSTART#)" ]
-                 then
-                     WRITE_DB=1
-                     WRITE_GEN=0
-                 fi
-             done
-             mv $DBCONF_TEMPFILE $DBCONF
-             mv $GENCONF_TEMPFILE $DBCONF
+
+             cat "$GENCONF" |  perl -ne ' $output=0 if /^\# \(\#DBEND\#\)/; print if $output; $output=1 if /^\# \(\#DBSTART\#\)/; ' >$DBCONF_TEMPFILE
+             cat "$GENCONF" | perl -ne '$output=1 if /^\#/; $output=1 if /^\# \(\#DBEND\#\)/; print if $output; $output=0 if /^\# \(\#DBSTART\#\)/;' >$GENCONF_TEMPFILE
+
+             # Be on the safe side, if we do not generate a non-empty
+             # configuration abort:
+             if [ -s "$GENCONF_TEMPFILE" ] ; then
+                 mv $GENCONF_TEMPFILE $GENCONF
+                 mv $DBCONF_TEMPFILE $DBCONF
+             else
+                 echo "ERROR: Preinstallation script was unable to extract a proper configuration file for migration. Please report this as a bug in the snort-common Debian package" >&2
+                 exit 1
+             fi
          fi
     ;;
     configure)
